# Generated by Django 4.1.3 on 2022-12-13 15:08

from django.db import migrations, models
import djongo.models.fields
import movie_hub.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("year", models.IntegerField()),
                (
                    "duration",
                    djongo.models.fields.EmbeddedField(
                        model_container=movie_hub.models.Duration
                    ),
                ),
                ("directors", djongo.models.fields.JSONField(default=[])),
                ("writers", djongo.models.fields.JSONField(default=[])),
                ("cast", djongo.models.fields.JSONField(default=[])),
                ("posterImage", models.URLField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("genres", djongo.models.fields.JSONField(default=[])),
                (
                    "imdb",
                    djongo.models.fields.EmbeddedField(
                        blank=True, model_container=movie_hub.models.IMDB
                    ),
                ),
                (
                    "comments",
                    djongo.models.fields.ArrayField(
                        blank=True, default=[], model_container=movie_hub.models.Comment
                    ),
                ),
            ],
        ),
    ]
