# Generated by Django 4.1.3 on 2022-12-14 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("movie_hub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="dateAdded",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
