# Generated by Django 4.1.3 on 2022-12-16 09:14

from django.db import migrations
from djongo.base import DatabaseSchemaEditor
import pymongo


def addMovieIndexes(_apps, schema_editor: DatabaseSchemaEditor):
    # Get pymongo db object
    mongoConnection = schema_editor.connection.Database.connect('movie_hub')
    db: pymongo.database.Database = mongoConnection['movie_hub']

    # Create dateAdded index
    db.movie_hub_movie.create_index(name='dateAdded_-1',
                                    keys=[('dateAdded', pymongo.DESCENDING)])

    # Create rating index
    db.movie_hub_movie.create_index(name='imdb.rating_-1',
                                    keys=[('imdb.rating', pymongo.DESCENDING)])

    # Create text index
    db.movie_hub_movie.create_index(name='title_cast_summary_genres_text',
                                    keys=[
                                        ('title', pymongo.TEXT),
                                        ('cast', pymongo.TEXT),
                                        ('summary', pymongo.TEXT),
                                        ('genres', pymongo.TEXT),
                                    ],
                                    weights={
                                        'title': 4,
                                        'cast': 2,
                                        'summary': 2
                                    })


def deleteMovieIndexes(_apps, schema_editor: DatabaseSchemaEditor):
    mongoConnection = schema_editor.connection.Database.connect('movie_hub')
    db: pymongo.database.Database = mongoConnection['movie_hub']

    # Drop dateAdded index
    db.movie_hub_movie.drop_index('dateAdded_-1')

    # Drop rating index
    db.movie_hub_movie.drop_index('imdb.rating_-1')

    # Drop text index
    db.movie_hub_movie.drop_index('title_cast_summary_genres_text')


class Migration(migrations.Migration):

    dependencies = [
        ("movie_hub", "0003_movie_parentsguide"),
    ]

    operations = [
        migrations.RunPython(code=addMovieIndexes,
                             reverse_code=deleteMovieIndexes)
    ]
