# Generated by Django 4.1.3 on 2022-12-17 19:35

from django.db import migrations
from django.apps.registry import Apps
from django.contrib.auth.models import User as UserT
from django.contrib.auth.hashers import make_password
from djongo.models.fields import ObjectId

id1 = 100
id2 = 101
id3 = 102


def insertUsers(apps: Apps, _schemaEditor):
    User = apps.get_model('auth', 'User')

    user1: UserT = User()
    user1.id = id1
    user1.username = 'norman02'
    user1.first_name = 'Norman'
    user1.last_name = 'Normanson'
    user1.password = make_password('asdASD123')
    user1.save()

    user2: UserT = User()
    user2.id = id2
    user2.username = 'thebob'
    user2.first_name = 'Bob'
    user2.last_name = 'Bobson'
    user2.password = make_password('asdASD123')
    user2.save()

    user3: UserT = User()
    user3.id = id3
    user3.username = 'aalice'
    user3.first_name = 'Alice'
    user3.last_name = 'Alison'
    user3.password = make_password('asdASD123')
    user3.save()


def dropUsers(apps: Apps, _schemaEditor):
    User = apps.get_model('auth', 'User')
    for i in [id1, id2, id3]:
        User.objects.get(pk=i).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("movie_hub", "0005_movie_moresummary"),
    ]

    operations = [migrations.RunPython(insertUsers, dropUsers)]
