# Generated by Django 4.1.3 on 2022-12-30 18:37

from django.db import migrations
from djongo.base import DatabaseSchemaEditor
import pymongo


def create_index(_apps, schema_editor: DatabaseSchemaEditor):
    mongoConnection = schema_editor.connection.Database.connect('movie_hub')
    db: pymongo.database.Database = mongoConnection['movie_hub']

    # Create a multikey index on comments date
    db.movie_hub_movie.create_index(name='comments.date_-1',
                                    keys=[('comments.date', pymongo.DESCENDING)
                                          ])

    # Sort comments
    db.movie_hub_movie.update_many({}, [{
        '$set': {
            'comments': {
                '$sortArray': {
                    'input': '$comments',
                    'sortBy': {
                        'date': -1
                    }
                }
            }
        }
    }])


def drop_index(_apps, schema_editor: DatabaseSchemaEditor):
    mongoConnection = schema_editor.connection.Database.connect('movie_hub')
    db: pymongo.database.Database = mongoConnection['movie_hub']

    # Drop the multikey index on comments date
    db.movie_hub_movie.drop_index('comments.date_-1')


class Migration(migrations.Migration):

    dependencies = [
        ("movie_hub", "0007_insert_movies"),
    ]

    operations = [migrations.RunPython(create_index, drop_index)]
